package Daje::Workflow::FileChanged::Activity;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;

use Daje::Config;
use Daje::Tools::Filechanged;
# NAME
#
# Daje::Workflow::FileChanged::Activity - It's new $module
#
# SYNOPSIS
# ========
#    use Daje::Workflow::FileChanged::Activity;
#
# DESCRIPTION
# ===========
#
# Daje::Workflow::FileChanged::Activity is ...
#
# LICENSE
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#


our $VERSION = "0.01";

sub changed_files($self) {

    my $filelist = Daje::Config->new(
        path => $self->context->{context}->{source_dir}
    )->load_list();

    my $filehash = Daje::Workflow::FileChanged::Database::Model::FileHashes->new(db => $self->db);
    $filelist->each(sub ($file, $num) {
        my $hash_data = $filehash->load_hash($file);
        unless (defined $hash) {
            my $hash = Daje::Tools::Filechanged->new()->load_new_hash($file);
            $filehash->save_hash($file, $hash);
        } else {

        }
    });

}

1;
__END__



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Workflow::FileChanged::Activity


=head1 SYNOPSIS

   use Daje::Workflow::FileChanged::Activity;



=head1 DESCRIPTION

NAME

Daje::Workflow::FileChanged::Activity - It's new $module


Daje::Workflow::FileChanged::Activity is ...

LICENSE

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.




=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS

=head2 changed_files($self)

 changed_files($self)();


=head1 AUTHOR

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

